apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}:{{ .Values.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: ENV_VAR_1
              value: {{ .Values.env.ENV_VAR_1 | quote }}
            - name: ENV_VAR_2
              value: {{ .Values.env.ENV_VAR_2 | quote }}
            # Add more environment variables as needed