apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  labels:
    app: {{ .Values.app }}
type: Opaque
data:
  # Replace with your actual secret data
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password}}